# Core configuration
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude

frontend:
  themes: !include_dir_merge_named themes

default_config:


# logger:
  # default: info
  # logs:
    # homeassistant.components.linak_desk_controller: debug

# Text to speech
tts:
  - platform: google_translate
    language: 'en'

lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /local/custom-lovelace/linak-desk/card.js
      type: module
    - url: /local/custom-lovelace/air-purifier/card.js
      type: module

automation: !include_dir_merge_list automations

ble_monitor: !include components/ble_monitor.yaml

climate: !include components/climate.yaml

discovery:
  ignore:
  - yeelight

fan: !include components/fan.yaml

group: !include groups.yaml

input_select: !include components/input_select.yaml

media_player: !include components/media_player.yaml

mqtt: !include components/mqtt.yaml

notify: !include components/notify.yaml

scene: !include scenes.yaml

script: !include_dir_merge_named scripts

sensor: !include_dir_merge_list sensors

speedtestdotnet: !include components/speedtestdotnet.yaml

recorder: !include components/recorder.yaml

yeelight: !include components/yeelight.yaml

vacuum: !include components/vacuum.yaml

influxdb:
  host: localhost
  include:
    entities:
      - sensor.mi_purifier_t
      - sensor.airly_temperature
      - sensor.ble_temperature_xiaomi1
      - sensor.ble_temperature_xiaomi2
