
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Core configuration
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: Europe/Warsaw

frontend: !include themes.yaml

# https://www.home-assistant.io/dashboards/dashboards/
lovelace:
  mode: yaml
  resources:
    - url: /local/xiaomi-vacuum-card.js
      type: module
    - url: /local/battery-entity.js
      type: module
    - url: /local/stack-in-card.js
      type: module
    - url: /local/air-purifier-card.js
      type: module

automation: !include_dir_merge_list automations

discovery:
  ignore:
  - yeelight

# Script for vacuum cleaner
input_select: !include components/input_select.yaml

# mqtt: !include components/mqtt.yaml

notify: !include components/notify.yaml

script: !include_dir_merge_named scripts

sensor: !include_dir_merge_list sensors

speedtestdotnet: !include components/speedtestdotnet.yaml

# recorder: !include components/recorder.yaml

yeelight: !include components/yeelight.yaml

# influxdb:
#   host: localhost
#   include:
#     entities:
#       - sensor.airly_temperature

binary_sensor: !include components/binary_sensor.yaml
