custom_header:
  compact_mode: true
  editor_warnings: false
  hide_help: true
  voice_hide: true
title: Home
views:
  - title: Home
    cards: !include lovelace/main.yaml
    path: home
    theme: Google Dark Theme
    icon: mdi:view-dashboard

  - title: Stats
    cards: !include lovelace/stats.yaml
    path: stats
    theme: Google Dark Theme
    icon: mdi:server-security

  # - title: Living Room
  #   cards: !include lovelace/living_room.yaml
  #   path: living room
  #   theme: Google Dark Theme
  #   icon: mdi:server-security

