title: Home
views:
  - title: Overview
    cards: !include lovelace/main.yaml
    path: home
    icon: mdi:home

  - title: Stats
    cards: !include lovelace/stats.yaml
    path: stats
    icon: mdi:server-security

  - title: Configuration
    cards: !include lovelace/test.yaml
    path: test
    icon: mdi:cog

  - title: Temperature
    cards: !include lovelace/temperature.yaml
    path: temperature
    icon: mdi:home-thermometer
