- platform: template
  sensors:
    # Air purifier sensors
    mi_purifier_aqi:
      friendly_name: "AQI"
      icon_template: mdi:database
      unit_of_measurement: 'AQI'
      value_template: "{{ state_attr('fan.air_purifier', 'aqi') }}"
    mi_purifier_h:
      friendly_name: "Humidity"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.air_purifier', 'humidity') }}"
    mi_purifier_t:
      friendly_name: "Temperature"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('fan.air_purifier', 'temperature') }}"