- platform: rest
  scan_interval: 900
  name: Airly
  resource: !secret airly_resource_link
  value_template: "{{ value_json['current']['values'][0]['value'] }} {{ value_json['current']['values'][1]['value'] }} {{ value_json['current']['values'][2]['value'] }} {{ value_json['current']['values'][3]['value'] }} {{ value_json['current']['values'][4]['value'] }} {{ value_json['current']['values'][5]['value'] }} {{ value_json['current']['indexes'][0]['level'] }} {{ value_json['current']['indexes'][0]['value'] }} {{ value_json['current']['indexes'][0]['description'] }}"
  headers:
    apikey: !secret airly_apikey

- platform: template
  sensors:
    # Airly sensors
    airly_pm1:
      friendly_name: "PM1"
      icon_template: mdi:jquery
      unit_of_measurement: "μg/m³"
      value_template: "{{ states.sensor.airly.state.split(' ')[0] }}"
    airly_pm25:
      friendly_name: "PM2.5"
      icon_template: mdi:jquery
      unit_of_measurement: "µg/m³"
      value_template: "{{ states.sensor.airly.state.split(' ')[1] }}"
    airly_pm25_norm:
      friendly_name: "PM2.5 norm"
      icon_template: mdi:jquery
      unit_of_measurement: "%"
      value_template: "{{ (states.sensor.airly.state.split(' ')[1] | float * 100 / 15.0) | round(0) }}"
    airly_pm10:
      friendly_name: "PM10"
      icon_template: mdi:jquery
      unit_of_measurement: "μg/m³"
      value_template: "{{ states.sensor.airly.state.split(' ')[2] }}"
    airly_pressure:
      friendly_name: "Pressure"
      icon_template: mdi:gauge
      unit_of_measurement: "hPA"
      value_template: "{{ states.sensor.airly.state.split(' ')[3] | float | round(1) }}"
    airly_humidity:
      friendly_name: "Humidity"
      icon_template: mdi:water-percent
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.airly.state.split(' ')[4] | float | round(0) }}"
    airly_temperature:
      friendly_name: "Temperature"
      icon_template: mdi:thermometer
      unit_of_measurement: "°C"
      value_template: "{{ states.sensor.airly.state.split(' ')[5] | float | round(1) }}"
    airly_quality:
      friendly_name: "Air quality"
      icon_template: mdi:quicktime
      unit_of_measurement: "CAQI"
      value_template: "{{ states.sensor.airly.state.split(' ')[6] }}"
    airly_aqi:
      friendly_name: "CAQI"
      icon_template: mdi:database
      unit_of_measurement: 'CAQI'
      value_template: "{{ states.sensor.airly.state.split(' ')[7] | float | round(1) }}"
    airly_description:
      friendly_name: "Info"
      icon_template: mdi:alert
      value_template: "{{ states.sensor.airly.state.split(' ')[8:] | join(' ') }}"
