- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: '/'
    - type: memory_use_percent
    - type: processor_use
    - type: load_5m
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: last_boot
    - type: swap_use_percent

- platform: command_line
  name: "Tinker Board CPU Temp"
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ (value | multiply(0.001)) | round(1) }}"
  scan_interval: 10

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: linak_desk
  mac: !secret linak_desk_mac
  min_height_m: 0.635
  max_height_m: 1.28
  scan_interval: 30