- alias: Turn on purifier if air is bad
  trigger:
  - above: '20'
    entity_id: fan.air_purifier
    for:
      minutes: 2
    platform: numeric_state
    value_template: '{{ state.attributes.aqi }}'
  # condition:
  #   conditions:
  #   - after: '1:00:00'
  #     before: '23:00:00'
  #     condition: time
  action:
  - data:
      message: "AQI {{ state_attr('fan.air_purifier', 'aqi') }}, turning on the Purifier!"
      title: "[HA] Jakość powietrza bardzo zła!"
    service: notify.notifier_mail_all
  - entity_id: fan.air_purifier
    service: fan.turn_on
  - entity_id: fan.air_purifier
    service: fan.set_speed
    data:
      speed: favorite
  - service: xiaomi_miio.fan_set_favorite_level       
    data_template:
      entity_id: fan.air_purifier
      level: >
        {% if state_attr('fan.air_purifier', 'aqi') | int > 80 %}
        14
        {% elif state_attr('fan.air_purifier', 'aqi') | int > 50 %}
        10
        {% elif state_attr('fan.air_purifier', 'aqi') | int > 30 %}
        5
        {% elif state_attr('fan.air_purifier', 'aqi') | int > 20 %}
        4
        {% elif state_attr('fan.air_purifier', 'aqi') | int > 15 %}
        3
        {% else %}
        2
        {% endif %}

- alias: Turn off purifier if air good
  trigger:
  - below: '15'
    entity_id: fan.air_purifier
    for:
      minutes: 1
    platform: numeric_state
    value_template: '{{ state.attributes.aqi }}'
  action:
  - entity_id: fan.air_purifier
    service: fan.turn_off